### ISSUE TITLE
dynamic matching of PivotNet

### ISSUE THREAD

**Issue by HerrYu123** [er-muyue/BeMapNet#20]
I have tried to reproduce the Pivot Dynamic Matching algorithm of PivotNet. But I find that it is very slow during training. Could you please give some optimization ideas or have I made some mistakes in my reproduction? Thanks in advance!

**Comment by wenjie710** [comment]
PivotNet is now available on [GitHub](https://github.com/wenjie710/PivotNet). Please feel free to explore, utilize, and raise issues.

**Comment by HerrYu123** [comment]
Wenjie, thanks a lot!
