### ISSUE TITLE
More Details of evaluation protocol

### ISSUE THREAD

**Issue by SibylGao** [er-muyue/BeMapNet#5]
Hi,  @er-muyue, thanks for your great work!

I've noticed that there is a huge performance gap between results of different evaluation protocol, but details of your own evaluation protocol are missing. Could you please provide more information? Thanks a lot!

**Comment by er-muyue** [comment]
Our code has been released from now, and you can see the details of the evaluation protocol from [here](https://github.com/er-muyue/BeMapNet/blob/cfea9e4c3737f363a4c43b5b6dd52061079d6730/tools/evaluation/eval.py#L35). 

BTW, we use the same evaluation protocol as [HDMapNet](https://github.com/Tsinghua-MARS-Lab/HDMapNet/tree/main/evaluation).

**Comment by SibylGao** [comment]
> Our code has been released from now, and you can see the details of the evaluation protocol from [here](https://github.com/er-muyue/BeMapNet/blob/cfea9e4c3737f363a4c43b5b6dd52061079d6730/tools/evaluation/eval.py#L35).
> 
> BTW, we use the same evaluation protocol as [HDMapNet](https://github.com/Tsinghua-MARS-Lab/HDMapNet/tree/main/evaluation).

Thx
